meta_product_name: "GoutsdFruits"
meta_title: "GoutsdFruits - La ferme fruitière bio à côté de Cerizay"
meta_description: "Commandez vos produits fruitiers à la ferme de Marie Gazeau !"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
